Feat: 카테고리 별 상품 조회 기능 구현
YesunPark/cafe-bom pull request #29
Opened 2023-08-25 22:57 UTC by sunlake123

### ☀️ 변경사항

**🌱 AS-IS**
카테고리 별 상품 조회 기능 필요

**🌷 TO-BE**
카테고리 별 상품 조회 기능 구현

### 🗣️ Comment
딱히 없습니다.

### ⚡️ 테스트
 
- [X] 테스트 코드
- [X] 전체 테스트 성공
- [X] API 테스트

2023-08-26 07:09 UTC, YesunPark requested changes
고생하셨습니다 테스트코드까지 가독성 좋게 작성해주셔서 리뷰하기 편했네요
그 카테고리 별 메뉴 보여줄 때 품절된 항목은 제외하고 보이게 해주셨는데
그 부분은 저희 요구사항 중 `품절된 상품의 경우 상품 리스트에서부터 품절 여부를 알 수 있다.` 에 안맞는 것 같아서 일단 request changes 걸어놨습니다 ㅠㅠ
 카테고리 별 메뉴목록 조회 시 품절된 상품도 보여주도록 수정만 해주시고 말씀해주시면 승인 날리도록 하겠습니다!

2023-08-26 07:09 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/product/controller/ProductControllerTest.java
> +
given과 when이 따로 주어지지 사용되지 않앗지만 삭제하지 않고 두신 이유가 혹시 있을까요??

2023-08-26 07:09 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/product/repository/ProductRepositoryTest.java
> +    @DisplayName("findAllByProductCategoryIdAndIsSoldOutFalse 성공")
이 부분 카테고리 별 품절되지 않은 상품 목록 조회 성공 이런식으로 변경하는게 displayName을 적는 이유에 부합하지 않나 싶습니다!

2023-08-26 07:09 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/product/service/ProductServiceTest.java
> +    @DisplayName("findProductList 성공")
요기도 한글로 이해하기 쉽게 작성해주시면 더 좋을 것 같아요!

2023-08-26 07:09 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/product/service/ProductServiceTest.java
> +        given(productRepository.findAllByProductCategoryIdAndIsSoldOutFalse(anyInt()))
참고로 given에 뭔가 줄 때 any~~를 사용하지 않는게 더 좋다고 하네요!
나중에 리팩토링 시 참고하시면 좋을 것 같아요 ㅎㅎ

2023-08-26 07:09 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/product/service/ProductServiceTest.java
> +        assertEquals(HttpStatus.BAD_REQUEST, customException.getErrorStatus());
저희 assertJ 문법으로 통일하기로 했으니 여기도 사용해서 작성해주시면 좋을 것 같습니다!
예시로 제가 개인프로젝트에서 작성한 코드 첨부드립니다
assertJ의 assertThatThrownBy 라는 문법사용하시면 돼요!
```
assertThatThrownBy(() -> accountService.createAccount(token, request))
            .isExactlyInstanceOf(CustomException.class)
            .hasMessage(TOKEN_NOT_MATCH_USER.getDescription());
```

2023-08-26 07:26 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/product/controller/form/ProductListForm.java
> +    public static class Response {
넵 request는 @PathVariable밖에 없습니다

2023-08-26 07:27 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/product/repository/ProductRepository.java
> +    List<Product> findAllByProductCategoryIdAndIsSoldOutFalse(Integer productCategoryId);
네 더 늦어지면 답답해질 것 같아서 먼저 올리긴 했는데 어디 적어두는게 좋긴 하겠네요..!

2023-08-29 16:32 UTC, sunlake123 commented
최종 수정 끝나고 푸시했습니다. 확인 부탁드려요!

2023-08-30 02:38 UTC, YesunPark approved these changes
승인했습니다! 고생하셨어요~~
추가 리뷰 참고부탁드려요!

2023-08-30 02:38 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/product/service/ProductService.java
> +    // wooyoung-23.08.22
어떤 서비스 메서드인지 설명도 부탁드립니다!
이름이랑 최근 수정 날짜만 쓰는거는 컨트롤러 메서드에요!
컨트롤러 메서드는 스웨거 어노테이션으로 설명이 되니까 이름이랑 날짜만 쓰기로 했었습니다 ㅎㅎ

2023-08-30 02:38 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/product/domain/entity/SoldOutStatus.java
> +    SOLD_OUT
요거 폴더 위치가 product - domain - entity 에 있는데
product - domain - type 으로 옮겨주세용!

2023-08-30 06:09 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/product/domain/entity/SoldOutStatus.java
> +    SOLD_OUT
오잉 이거 옮겨서 푸시했는데 아직 남아있네요 뭐지

2023-08-30 06:13 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/product/service/ProductService.java
> +    // wooyoung-23.08.22
수정하겠습니다

2023-08-30 06:32 UTC, merged