Refactor : 품절여부 컬럼의 boolean Type을 enum class ProductStatus 수정
YesunPark/cafe-bom pull request #30
Opened 2023-08-26 07:44 UTC by rkoji

### ☀️ 변경사항

**🌱 AS-IS**
- 상품의 품절여부의 컬럼을 boolean Type으로 생성

**🌷 TO-BE**
- boolean Type을 enum class ProductStatus 클래스 생성 후 수정

### 🗣️ Comment

### ⚡️ 테스트
 
- [ ] 테스트 코드
- [ ] 전체 테스트 성공
- [ ] API 테스트

2023-08-26 10:27 UTC, YesunPark requested changes
세터 때문에 request changes 달았습니다!
수고하셨어요 세터 이외의 리뷰는 참고만 하셔도 됩니당:)

2023-08-26 10:27 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/product/domain/entity/Product.java
> +@Builder(toBuilder = true)
혹시 toBuilder = true 옵션을 사용하신 이유가 있을까용?

2023-08-26 10:27 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/product/domain/entity/Product.java
> +@Setter
세터 삭제 부탁드립니다!

2023-08-26 10:27 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/product/domain/entity/Product.java
> +    private ProductStatus isSoldOut;
isSoldOut 컬럼명 수정 부탁드려요~
객체명도 ProductStatus는 어떤 상태인지 잘 파악이 안돼서 객체명이랑 컬럼명 둘다 SoldOutStatus 요런식으로 바꿔보면 어떨까 싶어요!

2023-08-27 01:18 UTC, bingsoo95 approved these changes
확인했습니다!

2023-08-27 03:05 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/product/domain/entity/Product.java
> +    private ProductStatus isSoldOut;
넵 반영해서 다시올리겠습니다!

2023-08-28 08:23 UTC, YesunPark commented
이렇게 자잘한거 변경할 때도 테스트코드 추가는 안하는 PR이라도 전체테스트는 한번 꼭 돌려주고 PR에 체크부탁드려요!

2023-08-30 02:41 UTC, YesunPark approved these changes

2023-08-30 02:51 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/product/domain/entity/SoldOutStatus.java
> +package com.zerobase.cafebom.product.domain.entity;
저희 enum 파일 domain.entity.type에 넣기로 했었던 것 같아요..!

2023-08-31 04:35 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/product/domain/entity/Product.java
> +@Builder(toBuilder = true)
@Builder메서드인데 toBuilder를 사용하면 기존 객체의 내용이 수정된다고 해서 사용했습니다
https://adjh54.tistory.com/96 참고글입니다!

2023-09-01 05:07 UTC, thsu1084 approved these changes

2023-09-01 06:28 UTC, sunlake123 approved these changes

2023-09-02 05:23 UTC, closed without merging