Youngseon/order history
YesunPark/cafe-bom pull request #31
Opened 2023-08-26 11:39 UTC by thsu1084

### ☀️ 변경사항

**🌱 AS-IS**
주문 내역 조회 기능 필요

**🌷 TO-BE**
주문 내역 조회 기능 구현

### 🗣️ Comment

제가 아직 많이 부족해서 잘못된 부분이 많을 텐데  알려 주시면 빠르게 수정하겠습니다!  

### ⚡️ 테스트
 
- [x] 테스트 코드
- [x] 전체 테스트 성공
- [x] API 테스트

2023-08-26 11:59 UTC, YesunPark requested changes
setter 사용, 주석 누락 등 빠진 부분이 있어서 request changes 추가했습니다!
너무 고생하셨습니다ㅠㅠ 혹시 코멘트 중 이해안되시는 부분 있으시면 말씀주세요!
영선님 다른 분들 PR 제목 확인하셔서 제목도 수정부탁드립니다~

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/common/BaseTimeEntity.java
> +    @Column(name = "modified_date")
요 부분은 굳이 추가 안해주셔도 이렇게 입력이 되는 부분입니다!

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +
저희 구글 스타일가이드에 맞춰서 하기로 했는데, 그걸로 적용하고 코드 정렬하면 아마 한칸만 띄워질 거에요!
코드 작성하시고 습관적으로 코드 정렬 눌러주시면 감사하겠습니다!
이 pr 내 파일들 다 한번 씩 코드 정렬 해주실 수 있을까요?

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +
코드 정렬 부탁드려요~

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +        }
저희 CustomException 사용하기로 해서, 그걸로 수정부탁드릴게요!
그래야 사용자에게 이 값들이 정해진 형식으로 나간답니당..!

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/repository/OrdersRepository.java
> +    List<Orders> findByMember(Member member); // findByMember 에서 MemberId 로 변경
요 부분은 나중에 수정될 부분이라 주석처리 하신건가요?
이런 사소한 부분들 PR 내용에 적어주시면 리뷰하기 더 좋을 것 같습니다 :)

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/repository/OrdersRepository.java
> +    List<Orders> findByMemberAndCreatedDateBetween(Member member, LocalDateTime startDate, LocalDateTime endDate);
레포지토리에 메서드 생성하는 경우 테스트코드 작성하기로 했어서 테스트코드 추가 부탁드립니다:)

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
> +@Transactional// 추가한 어노테이션
요런 개발용 주석은 삭제부탁드립니다

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
> +    public List<OrdersHisDto> findOrderHistoryFor3Months(Long memberId) {
컨트롤러랑 서비스 메서드에 붙이기로 한 주석 추가 부탁드려요

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
> +                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "사용자를 찾을수 없습니다"));
CustomException으로 변경 부탁드립니다. 혹시 다른 부분도 CustomException 안쓰셨으면 변경 부탁드려요
~

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersHisDto.java
> +@Setter
세터 삭제 부탁드립니다.

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersHisDto.java
> +    }
이거 from 메서드로 변경 부탁드립니다~

2023-08-26 11:59 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersHisDto.java
> +    }
요 부분은 비즈니스 로직인 것 같은데(List에 값을 추가하는 거보니) 어떤 로직이고 왜 여기에서 구현하신 건지 알 수 있을까요?

2023-08-26 11:59 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/history/controller/OrdersControllerTest.java
> +        // Given
저희 컨벤션에 맞게 given, when, then으로 변경 부탁드립니다!

2023-08-26 11:59 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/history/controller/OrdersControllerTest.java
> +    @Test
테스트코드에 DisplayName어노테이션, 작성자 주석도 추가부탁드립니다!

2023-08-26 11:59 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/history/service/OrdersHistoryServiceTest.java
> +    @BeforeEach
오 이렇게 BeforeEach로 먼저 생성하는 거 생각 안하고 있었는데
저도 적용해야겠네요! 타 개발자에게 설명하는 게 아닌 개발 시 사용했던 관련 주석들은 삭제부탁드립니다.

2023-08-26 11:59 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/history/service/OrdersHistoryServiceTest.java
> +    }
저희 assertJ 문법 사용하기로 했어서,
```
 assertThatThrownBy(() -> accountService.createAccount(token, request))
            .isExactlyInstanceOf(CustomException.class)
            .hasMessage(TOKEN_NOT_MATCH_USER.getDescription());
```

이런 식으로 assertThatThrownBy 메서드 사용해서 Exception 발생했는지 테스트해주시면 좋을 것 같습니다 ㅎㅎ

assertThrows는 그냥 junit 메서드로 알고있습니다!

2023-08-26 11:59 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/history/service/OrdersHistoryServiceTest.java
> +        assertEquals(1L, result.get(0).getOrderId());
assertThat 메서드 사용부탁드립니다~

2023-08-26 14:50 UTC, thsu1084 commented on src/test/java/com/zerobase/cafebom/history/service/OrdersHistoryServiceTest.java
> +        assertEquals(1L, result.get(0).getOrderId());
하나씩 다 보고 댓글 달아주셔서 감사합니다. 일단 수정하고 다시 커밋해서 push 하고 pr 날릴게요! 모르는 부분있으면 게더에 가서 여쭤보면 되는거죠!?

2023-08-29 09:13 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersHisDto.java
from을 사용하려고 했는데 이미 ControllerService에 from 함수가 있으니까 Orders 클래스의 객체를 매개변수로 받고 그런 다음 생성자 내부에서 주어진 Orders 객체의 속성을 사용하여 OrdersHisDto 객체를 초기화하는건 어떨까 해서요... 안될까요?!

2023-08-29 18:36 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +        }
viewType이 "기간"인데 시작 날짜와 마지막 날짜가 null이면 오류인 것까지는 이해했습니다. 그런데 예외가 MEMBER_NOT_EXISTS 로 처리되는 이유를 알 수 있을까요?

2023-08-29 18:43 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +        List<OrdersHisDto> orderHisDtoList;
OrderHistoryDto까지 풀네임으로 하는 게 좋지 않을까 싶습니다.

2023-08-29 18:49 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/orders/domain/entity/Orders.java
> +import static javax.persistence.FetchType.LAZY;
사용되지 않은 import문 자동 삭제 기능 쓰시면 FetchType.LAZY같이 사용하지 않은 import문은 자동 삭제됩니다!

2023-08-29 19:01 UTC, sunlake123 requested changes
리뷰하면서 코멘트 몇 개 달아보았습니다

어디 코드를 잡아서 말씀드려야 할지 애매해서 전체 코멘트로 남길게요!

저도 확신이 있는 부분은 아니지만 OrdersController에서 파라미터마다 if문으로 예외 처리나 orderHisDtoList에 사용되는 OrderService의 메서드를 나누셨는데

뭔가 이런 부분은 Service까지 넘겨서 처리하는 것이 어떨까 싶습니다. 공통적으로 "기간 혹은 전체", "시작과 끝 날짜"를 이용하는 메서드인데 비슷한 기능의 메서드가 Service단에 3개나 있고 memberRepository.findById()같은 메서드가 전부 반복되기도 하고 리턴도 return from(orders)로 동일하네요. findOrderHistory(Long memberId, LocalDate startDate, LocalDate endDate) 이런 식으로 Service단에서 메서드를 하나만 만들고 그 안에서 공통적으로 처리할 것은 처리하고 분기로 예외도 처리하는 것이 어떨까 싶어용.

Service의 메서드 이름들을 보면 Repository의 메서드를 그대로 이용해 Controller단까지 당겨 사용하는 느낌이 듭니다.

api, 테스트코드 전부 문제가 없다면 우선 머지하시고 추후에 리팩토링 하실 때 한 번 쯤 생각해보시면 좋을 것 같습니다!

2023-08-30 02:58 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +        List<OrdersHisDto> orderHisDtoList;
동의합니다. His 라는게 직관적으로 History라고 보이진 않네요!

2023-08-30 11:18 UTC, sunlake123 approved these changes

2023-08-31 08:16 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersProductDto.java
> +
칸 삭제해주시면 좋을거같아요!

2023-08-31 08:24 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
> +        List<Orders> orders = ordersRepository.findByMember(member); // findByMember 에서 MemberId로 변경
주석은 findByMemberId로 변경이라고 되어있는데 어떤게맞는걸까요??

2023-08-31 08:27 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersHisDto.java
이 로직은 Dto.에 Orders를  담고싶어서 그런건가요...?

2023-08-31 08:40 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/orders/service/dto/OrdersHisDto.java
orders엔티티에 있는 정보중에 사용자에게 보여줄 정보를 담아서 전달하는 용도입니다!

2023-08-31 08:42 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
> +        List<Orders> orders = ordersRepository.findByMember(member); // findByMember 에서 MemberId로 변경
이 건 제가 삭제하려고 했는데 빼먹었네요ㅠㅠ

2023-08-31 08:43 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
> +    public List<OrdersHisDto> findOrderHistoryFor3Months(Long memberId) {
어 수정 됐습니다! 주석 추가했어요!

2023-08-31 10:37 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
> +        List<Orders> orders = ordersRepository.findByMember(member); // findByMember 에서 MemberId로 변경
삭제 했습니다!

2023-08-31 10:47 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
> +    public List<OrdersHisDto> findOrderHistoryFor3Months(Long memberId) {
아 저는 
    // 관리자 상품 카테고리 등록-jiyeon-23.08.31 이런식으로 어떤 메서드인지 알 수 있게 적었고 다른분들도 그렇게하셨더라구요..!!! 참고하시면 좋을거같아요!

2023-08-31 11:51 UTC, YesunPark approved these changes
전체적인 주석 형식, 2~3줄 씩 있는 엔터만 수정해주시면 머지하셔도 될 것 같습니다 고생하셨습니다 :)

2023-08-31 11:51 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/common/BaseTimeEntity.java
> +
여기 여백들 추가된거 삭제 부탁드려요! 17번 1줄이랑 20번 1줄 ! ㅎㅎ

2023-08-31 11:51 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/member/domain/entity/Member.java
> +
여기도 삭제 부탁드립니다~

2023-08-31 11:51 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +
여기도 아직 코드 정렬이 안되어있습니다! ㅠㅠ ctrl + option + l 하시면 코드 정렬됩니당
엔터는 1줄씩만 부탁드려요 ㅠ

2023-08-31 11:51 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +    // youngseon 23.08.28
youngseon-23.08.28로 수정부탁드려요~

2023-08-31 11:51 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/domain/entity/Orders.java
> +
줄 삭제 부탁드립니다

2023-08-31 11:51 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersHistoryService.java
> +    public List<OrdersHisDto> findOrderHistoryFor3Months(Long memberId) {
영선님 서비스 코드에는 어떤 메서드인지도 주석에 적어주셔야 합니다 ㅎㅎ
위의 지연님 주석 샘플 참고부탁드려요

2023-08-31 11:51 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/history/service/OrdersHistoryServiceTest.java
> +    @Test
작성자 주석 추가 부탁드립니당

2023-08-31 11:51 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/orders/repository/OrdersRepositoryTest.java
> +  //youngseon 23-08-28
// youngseon-23.08.28
이렇게 형식 통일 부탁드립니다 😂

2023-09-01 14:22 UTC, bingsoo95 approved these changes
확인했습니다!

2023-09-03 12:36 UTC, merged