Feat : 관리자 상품 등록,조회,수정,삭제 기능 구현
YesunPark/cafe-bom pull request #32
Opened 2023-08-27 16:40 UTC by rkoji

### ☀️ 변경사항
**🌱 AS-IS**
관리자 상품 등록,조회,수정,삭제 기능 필요

**🌷 TO-BE**
관리자 상품 등록,조회,수정,삭제 기능 구현

### 🗣️ Comment
- S3관련된건 혹시 몰라서 주석으로 설명 달아뒀습니다
- 아직 test는 수정중이여서 다 성공하면 추가 commit하겠습니다

### ⚡️ 테스트
 
- [ ] 테스트 코드
- [ ] 전체 테스트 성공
- [ ] API 테스트

2023-08-28 08:04 UTC, YesunPark requested changes
확인했습니다 ㅎㅎ 저희 메서드명, 주석 컨벤션에 맞추는 거, 컨트롤러 uri 에 update,remove 단어빼는 거  제외하곤 참고만 해주셔도 됩니다ㅎㅎ!
일단 위에 언급드린 3부분은 수정되어야 하는 부분이라 request changes 달아주세요!!
아 그리고 다음엔 PR에 yml 파일 변경사항 있으면 PR에도 적고 노션에 전체 언급해서 따로 알려주세요
3명 승인해서 PR 확인을 못하는 분이 계실 수도있어서요 ㅎㅎ
고생하셨습니다~!

2023-08-28 08:04 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/product/service/ProductServiceImpl.java
> +    // 수정 서비스 - jiyeon-23.08.25
여기도... 서비스라는 말은 빼주시고 메서드 명도 update가 아닌 modify로 부탁드립니다~

2023-08-28 08:04 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/product/service/S3UploaderService.java
> +        // 파일의 콘텐츠 타입(형식)을 메타데이터에 설정
S3 관련한 주석 좋습니다 감사합니다!

2023-08-28 10:27 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/CafeBomApplication.java
> +)
넵! S3관련 설정입니다

2023-08-28 10:28 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/product/controller/ProductController.java
> +    @ApiOperation(value = "관리자 메뉴 전체조회", notes = "전체 리스트를 조회합니다.")
넵 참고해서 수정하겠습니다!

2023-08-28 10:33 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/product/controller/ProductController.java
> +    @PreAuthorize("hasRole('ADMIN')")
![image](https://github.com/YesunPark/cafe-bom/assets/101394751/65346b89-5755-42dd-8eec-a17d28a01cb6)
상관없는거같아요! Controller테스트하는데도 문제없더라구요!

2023-08-28 10:34 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/product/domain/entity/Product.java
> +    public void updateProduct(ProductForm productForm) {
넵 수정하겠습니다!

2023-08-28 10:34 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/product/service/ProductServiceImpl.java
> +    // 등록 서비스 - jiyeon-23.08.25
넵!

2023-08-28 10:34 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/product/service/ProductServiceImpl.java
> +    // 수정 서비스 - jiyeon-23.08.25
넵 수정하겠습니다!

2023-08-30 02:56 UTC, YesunPark approved these changes
Form validation 완전 꼼꼼하게 해주셨네요 저도 배워야겠어요!
api endpoint도 깔끔하게 수정됐네요 ㅎㅎ
고생하셨습니다~!

2023-08-30 02:56 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/product/controller/ProductController.java
> +    @PostMapping(value = "/add", consumes = MULTIPART_FORM_DATA_VALUE)
요 부분도 아예 /add value 없애주셔도 될 것 같습니다~!
그냥 POST /admin/product
라는 api 로 충분히 상품 등록이라는 게 전달이 됩니다!

2023-08-30 15:12 UTC, sunlake123 approved these changes
열심히 읽었습니다.

2023-08-31 17:45 UTC, YesunPark approved these changes
확인했습니다 :)

2023-09-02 07:17 UTC, merged