Feat: 주문 상태 변경 기능 완성
YesunPark/cafe-bom pull request #33
Opened 2023-08-28 00:33 UTC by bingsoo95

### ☀️ 변경사항

**🌱 AS-IS**
- 주문 상태 변경 기능 부재

**🌷 TO-BE**
- 관리자가 사용자의 주문 상태를 변경할 수 있는 기능을 구현했습니다.
- 사용자가 주문의 경과 시간을 조회할 수 있는 기능을 구현했습니다.

### 🗣️ Comment

- 많이 부족하지만 피드백 주시면 적극 반영해서 리팩토링 해보겠습니다!

### ⚡️ 테스트
 
- [ ] 테스트 코드
- [ ] 전체 테스트 성공
- [ ] API 테스트

2023-08-28 08:20 UTC, YesunPark requested changes
확인했습니다! 고생하셨어요 ㅎㅎ
전체적으로 코드가 가독성이 좋고 PR단위도 하나의 기능으로 적절해서 리뷰하기 편했네요!
그 테스트코드나 서비스, 컨트롤러 코드 메서드명 때문에 일단 request changes 로 변경했습니다.
수정하시고 슬랙에 태그해주시면 확인하고 apporve 하겟습니다!
나머지 부분은 참고만 해주셔도 될 것 같아요

2023-08-28 08:20 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
> +    ORDER_NOT_FOUND("해당 주문이 없습니다.", HttpStatus.NOT_FOUND),
Orders로 통일해주시면 더 좋지 않을 까 싶습니다 ! ㅎㅎ

2023-08-28 08:20 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
> +    NOT_COOKING_ORDER("조리 중인 주문이 아닙니다.", HttpStatus.BAD_REQUEST);
이 두개가 굉장히 비슷한 맥락의 에러메세지 같은데,
뭔가 되게 다른 메세지를 가지고 있어서 뭔가 통일하면 좋지 않을까 싶어요! 

예를 들어
ORDERS_NOT_COOKING_STATUS
ORDERS_ALREADY_COOKING_STATUS
뭐 대충 이런 느낌으로요..! 요건 단순 참고만 해주셔도 됩니다
나중에 리팩토링 하면 되는 부분이라서요!

2023-08-28 08:20 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +    public ResponseEntity<String> updateOrdersStatus(
컨트롤러 메서드명 컨벤션 참고부탁드립니다 :)
컨벤션에 따르면 ordersStatusModify() 라는 명의 메서드가 되어야하겠네요

2023-08-28 08:20 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +        ordersService.updateOrdersStatus(ordersId, OrdersStatusModifyDto.from(ordersStatusForm));
서비스 메서드명도 컨벤션 참고 부탁드리겠습니다~

2023-08-28 08:20 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +    @ApiOperation(value = "조리 경과 시간 조회", notes = "사용자가 조리 경과 시간을 조회합니다")
설명 너무 깔끔하고 가독성 좋은 것 같습니다!

2023-08-28 08:20 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +        return ResponseEntity.ok(elapsedTimeMinutes);
단순히 Long 타입을 반환하는 것이 아니라 객체를 반환해주면 나중에 서비스의 확장성 면에서도, 프론트가 정보를 활용하는 면에서도 더 좋을 것 같네요 ㅎㅎ
예를 들어 {elapsedTimeMinutes : 1}
이런 식으루요~

2023-08-28 08:20 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/domain/entity/Orders.java
> +    @Id
탭 간격 4로 바꾸셨군요 👍

2023-08-28 08:20 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/domain/entity/Orders.java
> +    public void updateReceivedTime(OrdersCookingStatus newStatus) {
요기도 update 말고 modify 부탁드립니다

2023-08-28 08:20 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +    public void updateOrdersStatus(Long orderId, OrdersStatusModifyDto ordersStatusDto) {
메서드명 컨벤션 확인 부탁드립니다 :)

2023-08-28 08:20 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +            .orElseThrow(() -> new CustomException(ORDER_NOT_FOUND));
여기도 Orders로 s 붙이게 통일하면 좋을 것 같습니다!

2023-08-28 08:20 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/orders/controller/OrdersControllerTest.java
> +            .andExpect(status().isOk())
저희 상태 변경성공 처럼 딱히 반환하는 객체가 없다면 200 ok 말고 204로 하기로 해서 ㅎㅎ isOk말고 수정 부탁드립니다!

2023-08-28 08:20 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/orders/controller/OrdersControllerTest.java
> +    @DisplayName("주문 상태 변경 실패 - 이미 조리 중인 주문 none으로 상태 변경 불가")
이 부분은 컨트롤러가 아니라 서비스에서 테스트해야 할 부분이라고 생각하는데 민수님은 어떻게 생각하시나요?
컨트롤러는 단순히 클라이언트의 요청 형식이 잘못됐거나 한걸 체크하는거고, 모든 요청을 형식에 맞게 잘 보냈으나 서비스에서 검증할 때 이미 조리 중인 주문에 대해 none으로 상태 변경을 요청하면 거기서 에러가 나야한다고 생각해서요!

2023-08-28 08:20 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/orders/controller/OrdersControllerTest.java
> +        given(ordersService.getElapsedTime(ordersId))
이것도 보시면 서비스에서 에러가 났다는 것을 이미 given으로 주고 있어서, 이것도 서비스의 영역 아닐까 하네요! 저도 정확한 건 아니라 헷갈리시면 controller, service 코드의 역할을 검색해보시거나 멘토님께 물어보시는 것도 좋을 것 같아요 ㅎㅎ

2023-08-28 12:17 UTC, bingsoo95 commented on src/test/java/com/zerobase/cafebom/orders/controller/OrdersControllerTest.java
> +    @DisplayName("주문 상태 변경 실패 - 이미 조리 중인 주문 none으로 상태 변경 불가")
넵 말씀해 주신 부분을 생각해보니 예외처리에 대한 테스트는 서비스 쪽이 맞는 것 같네요. 피드백 반영하겠습니다!

2023-08-30 03:02 UTC, YesunPark approved these changes
변경사항 잘 보았습니다 고생하셨습니다!

2023-08-30 04:05 UTC, rkoji approved these changes
확인했습니다!

2023-08-30 16:52 UTC, sunlake123 reviewed
잘 읽었습니다!

이건 전체적으로 말씀드려야 할 것 같아서 여기에 적습니다.
OrdersService의 36~39줄에서 ORDERS_ALREADY_COOKING_STATUS 예외가 이미 COOKING중인 상황에 NONE으로 되돌릴 수 없게 만드신 예외인 것 같은데요,
NONE -> COOKING -> PREPARED -> FINISHED 의 흐름에서
반대의 흐름으로 되돌릴 수 없게 막는 것이라면 COOKING -> PREPARED, FINISHED -> PREPARED로 가는 것도 예외 처리로 막아야 하지 않을까 싶습니다.

이게 관리자 기능이기도 하고 @RequestBody가 있는 PatchMapping이라 바디의 내용에 따른 예외처리도 전부 해야 하는지 애매하기 때문에... 민수님 의견을 듣고 싶습니다.

그리고 이건 제 개인적인 의견인데 만약 프론트가 있다고 가정할 시 NONE -> COOKING -> PREPARED -> FINISHED 으로 가는 버튼들이 매 단계마다 각각 있고 그 버튼이 "주문 상태 변경"이라는 요청으로 들어갈 거잖아요? 그럼 "주문 상태 변경" 이라는 기능 자체를
무조건 한 단계 앞으로 바꾸도록 하는 건 어떨까 싶습니다. 

예를 들면 NONE 상태에서 "조리 시작" 버튼을 누르면 NONE -> COOKING으로,
조리가 끝났다면 "조리 완료" 버튼을 눌러 COOKING -> PREPARED로,
손님이 상품을 수령해갔다면 "수령 완료" 버튼을 눌러 PREPARED -> FINISHED로 가는 느낌으로요. 그리고 이 모든 버튼들을 /admin/orders-status/{orderId}로 매핑하면 되지 않을까...하는 저의 생각입니다.

슬랙이나 댓글로 의견 주시면 감사하겠습니다!

2023-08-30 16:57 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +    public ResponseEntity<OrdersElapsedFindDto> elapsedTimeGet(@PathVariable Long ordersId) {
저희 컨트롤러에서의 Dto는 Form.Request나 Form.Response로 사용하기로 했어서 컨트롤러 응답은 Dto대신 Form이 어떨까 싶습니다!

2023-08-31 03:42 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +    public ResponseEntity<OrdersElapsedFindDto> elapsedTimeGet(@PathVariable Long ordersId) {
맞습니다! 컨트롤러에서 Client에게 응답을 줄때는 Form.Response 사용 부탁드립니다:)

2023-09-01 04:39 UTC, bingsoo95 commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +    public void updateOrdersStatus(Long orderId, OrdersStatusModifyDto ordersStatusDto) {
넵 관련 내용 추가하겠습니다!

2023-09-01 04:44 UTC, bingsoo95 commented on src/main/java/com/zerobase/cafebom/orders/controller/OrdersController.java
> +    public ResponseEntity<OrdersElapsedFindDto> elapsedTimeGet(@PathVariable Long ordersId) {
넵 변경하겠습니다.

2023-09-01 05:58 UTC, bingsoo95 commented
@sunlake123 우영님 말씀처럼 한 단계씩 상태변경을 줄 수 있게 된다면 확실히 불필요한 예외 처리도 줄일 수 있게 되고 좋은 것 같습니다. 수정해서 리뷰 다시 부탁드리도록 하겠습니다!

2023-09-02 09:16 UTC, bingsoo95 commented
@sunlake123 피드백 주신 부분들 수정했습니다. 확인 한번만 부탁드리겠습니다!

2023-09-02 17:39 UTC, sunlake123 commented
@bingsoo95 이게 어떤 코멘트는 댓글 기능이 없네요... 여기에 달게요!

고생하셨습니다..! 제가 제안한 방식은 엔드포인트를 /{ordersId}로 하면 newStatus를 요청에 받아오지 않고 `@PathVariable` 하나만 있어도 해당 id의 주문의 상태를 가져와서 다음 단계로 바꾸고, `FINISHED`상태라면 예외를 발생시키는 방식으로 가능할 것 같아서 말씀드렸습니다. 만약 이 방법도 괜찮다면 리팩토링 주간에 한 번 생각해보셔도 좋을 것 같아요. 승인으로 바꾸겠습니다. 수고하셨어요!

2023-09-02 17:39 UTC, sunlake123 approved these changes

2023-09-03 19:21 UTC, merged