Feat: 주문 저장(생성) 기능 구현
YesunPark/cafe-bom pull request #36
Opened 2023-08-29 00:37 UTC by YesunPark

### ☀️ 변경사항

**🌱 AS-IS**
- 주문 저장 기능 부재

**🌷 TO-BE**
- 사용자에게 토큰과 주문정보(결제 방식, 주문한 상품, 주문한 옵션)를 받아 주문을 저장(생성)하는 기능 구현
- 주문 생성 컨트롤러, 서비스 테스트코드 작성
- 컨트롤러 테스트코트 실패 케이스
   - 헤더에 Authorization 없음
   - 요청 형식 오류(결제 수단 누락)
   - 상품 ID 범위 이탈 => 현재 테스트 실패중이라 추후 수정하려고 임시 주석처리. 리팩토링 기간에 수정하고 주석 풀겠습니다.
- 서비스 테스트코드 실패 케이스
   - 존재하지 않는 회원 ID로 요청
   - 존재하지 않는 상품 ID로 요청
   - 존재하지 않는 옵션 ID로 요청

### 🗣️ Comment

- `@DisplayName("주문 저장 실패 - 상품 ID 범위 이탈")`테스트는 오류가 조금 있어서 추가적으로 수정이 들어가야 할 것 같습니다. 나중에 리팩토링 해도 되는 부분일 것 같아서 일단 PR 올립니다!
- 한 서비스에 여러개의 레파지토리가 물려있어서 이렇게 구현하는게 맞는지 궁금합니다ㅠㅠ 피드백이나 질문 마구마구 주세요
- 테스트코드에서 빠진 실패케이스가 있다면 편하게 말씀주세요!

### ⚡️ 테스트
 
- [x] 테스트 코드
- [x] 전체 테스트 성공
API 테스트 => 옵션 생성, 상품 생성 기능이 없어서 실제 api 테스트는 아직 진행 못함.

2023-08-29 11:58 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
> +    PRODUCT_NOT_EXISTS("존재하지 않는 상품입니다.", HttpStatus.BAD_REQUEST),
제가 올린 PR에는 PRODUCT_NOT_FOUND로 만들었었는데 아마 같은 응답이겠죠?

2023-08-30 03:04 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
> +    PRODUCT_NOT_EXISTS("존재하지 않는 상품입니다.", HttpStatus.BAD_REQUEST),
앗 맞습니다. 이 부분은 나중에 머지되고 리팩토링 때 통합하는 형식으로 하는게 좋을 것 같네요!
@sunlake123

2023-08-30 17:34 UTC, sunlake123 commented
잘 읽었습니다!

제가 생각했던 방식이랑 달라서 코멘트 남깁니다.

예선님 코드를 보니까 컨트롤러에서 주문하고자 하는 상품과 그에 따른 옵션들까지 Form에 매핑돼서 `@RequestBody`에 담겨있는데요,
그럼 사용자가 장바구니 목록 조회를 하고 있는 상태창에서 '주문' 버튼을 누르면 프론트단에서 그 화면 상의 장바구니 목록에 있는 상품들과 그 상품에 딸려있는 옵션들까지 긁어서 `@RequestBody`에 넣어 요청을 하는 구조인 건가요?

뭔가 저는 요청에 담긴 토큰에 있는 id만 이용해서 장바구니 -> 장바구니_옵션 -> 옵션 에 담긴 "사용자 id가 장바구니에 담아놓은 상품(옵션)"들을 그대로 꺼내와서 주문_상품, 주문_상품_옵션에 담는다고 생각하고 있었습니다.

즉

장바구니 <-> 주문_상품
장바구니_옵션 <-> 주문_상품_옵션

이 대응됨을 이용해서 장바구니에 담긴 유저의 상품(옵션까지)를 그대로 주문_상품, 주문_상품_옵션에 옮긴다는 느낌이라고 생각했습니다. (결제된 시점에서 장바구니 내용물은 전부 삭제)

큰 틀은 같기 때문에 예선님 방식으로도 기능상 문제는 없지만 뭔가.. 장바구니 ~ 옵션까지의 테이블은 사용자가 자신의 장바구니를 확인하는 용도 말고는 쓰임새가 없는 것 같아서 문득 생각이 들었습니다.

예선님께 여쭤보고 싶은 제 의견이니 답변 기다립니다! 이게 뭔가 말로 여쭤보고 싶은데 늦은 시간이라 애매하네요.

2023-08-30 23:20 UTC, YesunPark commented
> 잘 읽었습니다!
> 
> 제가 생각했던 방식이랑 달라서 궁금한 게 있어 여쭙습니다.

우영님 완전 제가 놓쳤네요! 생각해보니까 저희 사용자는 장바구니에 있는 상품을 선택해서 주문하는게 아니라
장바구니에서 뭘 주문할 지 다 정한 다음, 주문할 때는 장바구니에 있는 모든 상품을 주문하는 거였죠...!
이 부분 바로 수정 들어가겠습니다! 저희 요구사항에 따르면 그렇게 하는게 맞는 것 같아요!
@sunlake123

2023-08-31 03:52 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/orders/controller/form/OrdersAddForm.java
> +    private List<ProductOrderedForm> products;
이 부분도 결제 수단에 관련된 내용인걸까요???

2023-08-31 03:55 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/orders/controller/form/OrdersAddForm.java
> +    private List<ProductOrderedForm> products;
항목?! 이런식으로 바꾸는것도 나쁘지않을겉아서요,,!

2023-08-31 05:03 UTC, bingsoo95 reviewed
컨벤션에 맞게 코드들이 잘 작성되어 있어서 코드를 읽으며 기능구현의 흐름을 이해하기 쉬웠던거 같습니다.작성하시느라 고생하셨습니다!

2023-08-31 06:28 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/controller/form/OrdersAddForm.java
> +    private List<ProductOrderedForm> products;
@rkoji 맞아요 오타였는데 지금은 기능 수정돼서 없어진 코드입니다!

2023-08-31 06:30 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +                Product productById = productRepository.findById(product.getProductId())
저 52번째 줄의 product가 product Entity가 아니라 ordersAddDto 내의 products 라는 변수의 네이밍이라 제가 구분하기 쉽도록 저렇게 한 것 같아요! 근데 지금은 우영님 리뷰 보고 기능 수정한 상태라 dto 구조가 완전히 바뀌어서 없는 코드가 되었습니당ㅎㅎ

2023-08-31 06:47 UTC, thsu1084 approved these changes
일단 노션에 나와있는 컨벤션 보면서 확인했는데 잘 작성하신 것 같습니다!
고생하셨습니다!

2023-08-31 07:10 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +        Member memberById = memberRepository.findById(userId)
이부분 저는 이제까지 memberRepository.findByMemberId()로 줄곧 써왔는데 이렇게 메서드 명에 외래키를 직접 사용하면 결과는 같지만 불필요한 Join이 발생된다네요...! 이렇게도 되는구나 하고 신기해서 검색해봤는데 좋은 것 알아갑니다. 제 코드도 수정이 필요하겠네요.

2023-08-31 07:12 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +        List<Cart> cartListByMember = cartRepository.findAllByMember(memberById);
이부분 저는 이제까지 cartRepository.findAllByMemberId()로 줄곧 써왔는데 이렇게 메서드 명에 외래키를 직접 사용하면 결과는 같지만 불필요한 Join이 발생된다네요...! 이렇게도 되는구나 하고 신기해서 검색해봤는데 좋은 것 알아갑니다. 제 코드도 수정이 필요하겠네요.

2023-08-31 07:20 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +                .build());
여기서 OrdersProduct에 있는 builder가 .ordersId()길래 OrdersProduct 엔티티에 가보니까 필드에 `@ManyToOne`으로 Orders orders가 매핑이 돼있는 게 아니라 Long ordersId;로 되어있네요?

엔티티에서 주문_상품 테이블과 주문 테이블을 N:1로 매핑하고 72번째 줄이 .orders(savedOrders) 가 되어야 할 것 같습니다. 제 로컬 메인에도 OrdersProduct가 이미 들어와있는 걸 보니 리뷰할 때 놓친 상태로 승인이 됐나 봅니다 ㅠㅠ

2023-08-31 07:26 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +                        .ordersProductId(Long.valueOf(cart.getProduct().getId()))
이 부분도 OrdersProductOption 엔티티에 OrdersProduct ordersProduct가 아닌 Long ordersProductId가 들어가 있네요.

2023-08-31 07:39 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +    }
이부분은 음... 어떻게 생각하느냐에 따라 다를 것 같은데 주문테이블에 주문이 생성이 되어도 저희가 취소여부 컬럼이 있어서 관리자가 취소를 하게 되면 주문이 취소되는데

장바구니에 담겨있었던 상품들을 "주문이 생성되었을 때" 지울지, 아니면 "주문이 결제 완료되었을 때" 지울지에 따라 다른 것 같습니다.

우선 api 명세에서 주문 - 결제 프로세스를 보면 
주문 완료(주문 생성, 결제 대기) -> 관리자가 수락 -> 결제 완료(장바구니 삭제) 혹은
주문 완료(주문 생성, 결제 대기) -> 관리자가 취소 -> 결제 취소(장바구니 유지) 가 될 것 같은데

이런 식이라면 장바구니 삭제 기능은 관리자가 ReceiptStatus를 변경하는 로직에 들어가야 하지 않나 싶습니다.

2023-08-31 07:41 UTC, sunlake123 requested changes
코멘트들 읽어주시면 감사하겠습니다!

2023-08-31 07:51 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +    }
저도 동의하는게 주문이 생성되는 로직에서 장바구니 정보를 삭제한다면 추후 주문을 취소당했을때 
혹은 저희 서비스 구현은 안하는거같지만 내가 주문을 취소했을때 장바구니가 삭제되면 안될거같습니다!
이런경우에는 메서드를 따로만들어서 우영님이 말씀해주신것처럼 주문상태가 조리중? 이런식으로 변경되면 그때 삭제가되는 로직을 따로만들어야할거같습니다!

2023-08-31 09:32 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +        List<Cart> cartListByMember = cartRepository.findAllByMember(memberById);
앗 저는 그런부분은 모르고 했었는데 관련 이슈가 있나보네요 저도 찾아봐야겠어요ㅎㅎ 감사합니다

2023-08-31 09:36 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +                .build());
이거 슬랙에 언급했던 부분입니다!
관계가 있는 테이블이 모두 many to one으로 매핑이 되어야하는 건 아닌데, 특히나 이렇게 중간테이블 역할을 하고 있는 OrdersProduct에서는 Orders의 ID만 알면되지 Orders의 객체 정보(결제수단, 취소 상태, 요리 상태)등을 알 필요가 없다고 생각해서 id만 묶었습니당

개인 프로젝트때도 고민했던 부분인데 멘토님께서 모두 연관관계로 매핑을 할 필요는 없고, 어떠한 상황에서 매핑이 필요한지 잘 고민해보라고 하셨던 기억이 나서 고민 후 id만 묶는다고 말씀드렸던 것입니다!

혹시 우영님이 생각하시는 이 엔티티에서 Orders를 id가 아니라 객체로 묶어야 하는 이유가 있다면 설명 부탁드려요 참고하겠습니다 :)

2023-08-31 09:36 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +                        .ordersProductId(Long.valueOf(cart.getProduct().getId()))
넵 윗부분과 동일한 이유입니다

2023-08-31 09:37 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +    }
저는 보통 배달어플에서 주문이 취소당했을 때, 혹은 쿠팡에서 판매자 사유로 주문이 취소당했을 때 주문이 취소당한 내역은 주문내역에서 남지만 그 취소당했던 상품들이 장바구니에 다시 생기는 경험을 한 적은 없어서 이렇게 구현했었습니다

이 부분은 데일리미팅때 안건으로 다시 내겠습니다! 꼼꼼하게 봐주셔서 감사합니다 ㅎㅎ

2023-08-31 10:50 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/orders/service/OrdersService.java
> +                .build());
아 전에 미팅에서 들었던 기억이 나는 것 같네요. 그게 이 의미였군요! 죄송합니다 ㅜ.ㅜ

2023-08-31 18:33 UTC, sunlake123 commented
> @sunlake123 request changes는 그 장바구니 삭제 로직때문에 걸어주신 걸까요?

2023-08-31 18:34 UTC, YesunPark commented
@sunlake123 엥 우영님 제 pr 왜 닫으셨죠 ㅠㅠ

2023-08-31 18:35 UTC, sunlake123 commented
폰으로 답장하다가 그만..

2023-08-31 18:36 UTC, YesunPark commented
@sunlake123 ㅋㅋ제가 다시 열게요~

2023-08-31 18:38 UTC, sunlake123 commented
네네 죄송해요 ㅜㅜ
그 제가 테이블 매핑 착각했을때 request changes 걸어놨는데 깜빡했네요..! 승인으로 돌려놓겠습니당

2023-08-31 18:38 UTC, sunlake123 approved these changes

2023-09-01 04:51 UTC, rkoji approved these changes
확인했습니다!

2023-09-01 04:58 UTC, merged