add cart and basket
YesunPark/cafe-bom pull request #4
Opened 2023-08-14 13:13 UTC by thsu1084

### ☀️ 변경사항

**🌱 AS-IS**
cart Entity 필요

**🌷 TO-BE**

cart Entity 2개 생성

### 🗣️ Comment

### ⚡️ 테스트
 
- [ ] 테스트 코드
- [ ] 전체 테스트 성공
- [ ] API 테스트

2023-08-15 17:19 UTC, YesunPark commented
영선님 ~~~ 커밋 메세지가 전부 컨벤션과 어긋나요ㅠㅠ
저희 컨벤션 중 커밋 컨벤션 확인 부탁드릴게요!

2023-08-15 17:22 UTC, YesunPark commented
그리고 피드백 기반으로 수정중이신 거면 피드백 반영 중 라벨 붙여주세요! 피드백 반영 다 끝나면 리뷰요청 라벨 달아주세요! ㅎㅎ

2023-08-19 12:06 UTC, thsu1084 commented on src/main/java/com/zerobase/CafeBom/cart/domain/entity/Cart.java
제가 Integer 로 써야하는데 int로 했네요ㅠㅠ 이건 바로 수정하겠습니다.
혹시 또 잘못된 부분 있다면 남겨주세요! 빠르게 수정하겠습니다!

2023-08-19 12:06 UTC, thsu1084 commented on src/main/java/com/zerobase/CafeBom/cart/domain/entity/Cart.java
> +    private int count;
Integer 로 해야하는데 int를 사용했네요ㅠㅠ 수정하겠습니다!

2023-08-19 12:08 UTC, thsu1084 commented on src/main/java/com/zerobase/CafeBom/cart/domain/entity/Cart.java
> +}
이 부분도 is_ordered라고 수정하겠습니다!

2023-08-19 12:15 UTC, YesunPark commented
수정사항 다 반영되면 다시 리뷰요청 달아주세용

2023-08-19 12:35 UTC, YesunPark requested changes

2023-08-19 12:35 UTC, YesunPark commented on src/main/java/com/zerobase/CafeBom/cart/domain/entity/Cart.java
> +}
앗...entity에는 isOrdered라고 해주셔야해용 ㅠㅠ
is_ordered는 디비에 들어가는 네임이랍니당!!

2023-08-19 12:35 UTC, thsu1084 commented on src/main/java/com/zerobase/CafeBom/cart/domain/entity/Cart.java
> +}
넹! 알려주셔서 감사해요

2023-08-19 12:38 UTC, thsu1084 commented on src/main/java/com/zerobase/CafeBom/cart/domain/entity/Cart.java
> +}
이 부분만 고치면 머지 가능할까요?

2023-08-19 12:40 UTC, sunlake123 commented on src/main/java/com/zerobase/CafeBom/cart/domain/entity/Cart.java
> +}
boolean도 wrapper class로 부탁드리겠습니다!

2023-08-19 12:43 UTC, thsu1084 commented on src/main/java/com/zerobase/CafeBom/cart/domain/entity/Cart.java
> +}
네 수정했습니다!

2023-08-20 00:30 UTC, rkoji approved these changes

2023-08-20 04:49 UTC, YesunPark approved these changes
확인했습니다!

2023-08-20 09:12 UTC, sunlake123 commented on src/main/java/com/zerobase/CafeBom/cart/repository/CartRepository.java
> +
@Repository 어노테이션이 빠진 것 같아요

2023-08-20 09:14 UTC, thsu1084 commented on src/main/java/com/zerobase/CafeBom/cart/repository/CartRepository.java
> +
아 감사합니다!

2023-08-20 09:28 UTC, sunlake123 approved these changes

2023-08-20 12:18 UTC, merged