Feat : 관리자 Option 등록 기능 생성
YesunPark/cafe-bom pull request #40
Opened 2023-08-30 06:08 UTC by rkoji

### ☀️ 변경사항
**🌱 AS-IS**
- 관리자가 Option을 등록하는 기능 부재

**🌷 TO-BE**
- 관리자가 Option을 등록하는 기능 생성

### 🗣️ Comment
- API테스트까지는 다했지만 제가 아직 테스트 코드를 작성하는데 미숙해서 테스트 코드를 구현하다보면 시간이 오래걸릴거같아 일단 테스트코드는 나중에 작성해서 따로 PR올리겠습니다..!
- @PreAuthorize("hasRole('ADMIN')") 은 나중에 DB사용하게되면 그때 주석풀겠습니다!

### ⚡️ 테스트
- [ ] 테스트 코드
- [ ] 전체 테스트 성공
- [x] API 테스트

2023-08-30 11:23 UTC, YesunPark requested changes
확인했습니다!
컨트롤러에서 옵션 등록하는 부분에서 리턴값이 잘못된 것 같아서 request changes
달겠습니다 ㅠㅠ 수정 후 말씀해주세요!

2023-08-30 11:23 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/option/controller/OptionController.java
> +    }
지연님 저희 프로젝트 구조에서는
Client -> Controller(Form.Request -> Dto) -> Service (Dto) -> Controller(Dto -> Form.Response) -> Client
이런 구조로 프로젝트를 구성하고 있는데

지금 지연님의 프로젝트 구조와는 안맞는 것같습니다.
지연님 같은경우에는 단순히 옵션을 등록하는 api 인데 controller 에서 service로 form 을 전달하고, 서비스단에서 dto를 반환하고 받은 dto에 대해서 controller 단에서 검증을 하는 것이 옳지 않다고 봅니다.

수정하셔야 될 부분은
service에서는 반환할 값이 없기때문에 void로 변경해주시고 
if (optionAddDto.getId() != null) {
            return new ResponseEntity<>(OK);
        } else {
            return new ResponseEntity<>(OPTION_ADD_FAIL, BAD_REQUEST);
이 부분은 지워주시고 service 단에서 Optinal로 반환되는 .orElseThrow를 통해 예외처리를 해주시면 될 것같습니다.

Controller 에서의 OptionAdd 의 메서드의 내용에는
optionServcie.addOption(OptionAddDto.of(optionAddform));
return ResponseEntity.status(204).build();
이 두줄로 변경해주시면 될 것같습니다.

2023-08-30 11:23 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/option/service/OptionServiceImpl.java
> +
저희가 CustomException 으로 예외 처리를 날리기로 했던 부분이라서 
.orElseThrow(() -> new CustomException(NOT_FOUND_OPTION_CATEGORY);
이렇게 수정해주시면 될 것같습니다.

2023-08-30 11:23 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/option/service/OptionServiceImpl.java
> +            Integer optionCategoryId = optionAddForm.getOptionCategory();
서비스에 매개변수로 들어오는 건 Form 이 아니라 Dto여야 합니다! 
컨트롤러에서 Form을 Dto로 변경 후 서비스코드에 넘겨주세요~~

2023-08-31 04:18 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/option/controller/form/OptionAddForm.java
> +@Builder
요청 Form에 `@Builder`가 혹시 필요한가요?

2023-08-31 04:19 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/option/controller/form/OptionAddForm.java
> +    }
여기 `@Builder` 어노테이션이랑 생성자가 쓰이는 곳이 있는지 IDE에서 볼 수가 없어서 모르겠는데 넣으신 이유가 있으실까요?

2023-08-31 04:26 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/option/service/OptionServiceImpl.java
> +    // 옵션 등록-jiyeon-23.98.30
98 여기 시간 나시면 바꿔주세요! ㅋㅋ

2023-08-31 04:28 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/option/service/dto/OptionAddDto.java
> +    private Integer optionCategory;
여기 Integer가 맞다면(ServiceImpl을 보니 id가 맞는 것 같네요) optionCategoryId가 되어야 하지 않을까요?!

2023-08-31 04:39 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/option/service/OptionServiceImpl.java
> +    // 옵션 등록-jiyeon-23.98.30
아..!넵!

2023-08-31 04:39 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/option/service/dto/OptionAddDto.java
> +    private Integer optionCategory;
그러네요! 확인감사합니다

2023-08-31 04:39 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/option/controller/form/OptionAddForm.java
> +    }
API테스트를 진행하는데
Cannot construct instance of com.zerobase.cafebom.option.controller.form.OptionForm (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
OptionForm 클래스에 기본 생성자가 없어서 JSON 데이터를 객체로 변환할 수 없다라는 오류가 발생해 생성자를 생성해줫는데 다른방법을 모르겠어서요..!
이렇게 만들어주면 오류없이 API테스트 성공하긴했습니다..! @Builder를 빼고는 확인못해봤네요 한번 테스트해보고 커밋하겠습니다

2023-08-31 07:03 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/option/controller/form/OptionAddForm.java
> +    }
아 이오류가 나는게 Builer어노테이션때문이네요 삭제하고 커밋했습니다!

2023-08-31 17:50 UTC, YesunPark approved these changes
다시 확인했습니당! 고생하셨어요 :)

2023-09-01 12:36 UTC, sunlake123 approved these changes
승인했습니다!

2023-09-01 12:40 UTC, bingsoo95 approved these changes
확인 완료했습니다!

2023-09-02 03:52 UTC, merged