Feat : 관리자 옵션 카테고리 등록 기능 추가
YesunPark/cafe-bom pull request #63
Opened 2023-09-09 08:00 UTC by rkoji

### ☀️ 변경사항
**🌱 AS-IS**
- 관리자 옵션 카테고리 등록 기능 부재

**🌷 TO-BE**
- 관리자 옵션 카테고리 등록 기능 추가

### 🗣️ Comment
- @PreAuthorize("hasRole('ADMIN')") 이 될지 안될지에 따라 테스트코드가 달라질거같아 테스트코드는 추후에 올리겠습니다.

### ⚡️ 테스트
- [ ] 테스트 코드
- [x] 전체 테스트 성공
- [x] API 테스트

2023-09-09 16:51 UTC, YesunPark requested changes
확인했습니다! 
admin 패키지로 이동하는 것 때매 request changes 걸었습니다
수정 후 태그해서 알려주세요!

2023-09-09 16:51 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionCategoryController.java
> +    public ResponseEntity<Void> addOptionCategory(AdminOptionCategoryForm.Request optionCategoryFormRequest) {
컨트롤러 네이밍 규칙에 맞지 않습니다 확인 부탁드려요!
add 가 뒤에 가야 합니다

2023-09-09 16:51 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/option/controller/OptionController.java
> +@Tag(name = "option-controller", description = "관리자 옵션 CRUD API")
저희 스웨거 규칙에 따르면 admin-option-controller가 되어야하지 않을까요?
OptionController도 admin 폴더로 옮긴 후 AdminOptionController가 되어야 할 것 같습니다!

2023-09-10 02:55 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/option/controller/OptionController.java
> +@Tag(name = "option-controller", description = "관리자 옵션 CRUD API")
@YesunPark 제가 main병합하기전 커밋을 푸시해서 수정이안되어있었네요! 지금 수정해서 올린커밋에는  admin-option-controller로 바꾼게 안나와있지만 변경해놨습니다!

2023-09-11 02:40 UTC, rkoji commented
@YesunPark 수정했습니다 확인해주세요!

2023-09-11 05:04 UTC, bingsoo95 approved these changes
확인했습니다!

2023-09-11 06:54 UTC, YesunPark approved these changes
확인했습니다!!! 코멘트만 확인 부탁드려요

2023-09-11 06:54 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionCategoryController.java
> +@Tag(name = "admin-option-controller", description = "관리자 옵션 카테고리 CRUD API")
admin-option-category-controller 라고 수정 부탁드립니다~!

2023-09-11 06:54 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/auth/service/AdminOptionCategoryServiceImpl.java
> +    // 관리자 옵션 카테고리 등록 -jiyeon-23.09.05
등록과 - 사이에 붙여주세요!

2023-09-11 07:27 UTC, thsu1084 approved these changes
확인했습니다!

2023-09-11 08:27 UTC, merged