Feat : 관리자 옵션 카테고리 삭제, 조회 기능 추가
YesunPark/cafe-bom pull request #65
Opened 2023-09-09 09:01 UTC by rkoji

### ☀️ 변경사항
**🌱 AS-IS**
- 관리자 옵션 카테고리 삭제, 조회 기능 부재

**🌷 TO-BE**
- 관리자 옵션 카테고리 삭제, 조회 기능 추가

### 🗣️ Comment
- @PreAuthorize("hasRole('ADMIN')") 이 될지 안될지에 따라 테스트코드가 달라질거같아 테스트코드는 추후에 올리겠습니다.

### ⚡️ 테스트
- [ ] 테스트 코드
- [x] 전체 테스트 성공
- [x] API 테스트

2023-09-09 17:37 UTC, YesunPark requested changes
에러코드만 수정 부탁드리겠습니다~!

2023-09-09 17:37 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionCategoryController.java
> +
줄바꿈 삭제 부탁드립니다~!

2023-09-09 17:37 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/admin/service/AdminOptionCategoryServiceImpl.java
> +                .orElseThrow(() -> new CustomException(NOT_FOUND_OPTION_CATEGORY));
에러코드 컨벤션에 맞게 ~~NOT_EXISTS 
로 수정 부탁드립니다~!

2023-09-09 17:37 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/admin/service/AdminOptionCategoryServiceImpl.java
> +        AdminOptionCategoryDto.Response optionCategoryDto = AdminOptionCategoryDto.Response.from(optionCategory);
여기도 부탁드립니다

2023-09-11 08:42 UTC, rkoji commented
@YesunPark 수정했습니다 확인부탁드려요!

2023-09-11 08:43 UTC, YesunPark approved these changes
넵 고생하셨습니다!😆😆

2023-09-11 09:43 UTC, bingsoo95 approved these changes
확인했습니다. 고생하셨습니다!

2023-09-11 10:32 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionCategoryController.java
> +    public ResponseEntity<Void> OptionCategoryRemove(Integer optionCategoryId) {
이거 `@PathVariable` 생략이 가능한가요?

2023-09-11 10:34 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionCategoryController.java
> +    public ResponseEntity<Void> OptionCategoryRemove(Integer optionCategoryId) {
아 저도 방금 전체테스트 확인하다가 찾아서 수정했습니다!
다시 커밋해서 올리겠습니다

2023-09-11 10:54 UTC, thsu1084 approved these changes
확인했습니다!

2023-09-11 11:11 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/admin/controller/AdminOptionCategoryController.java
> +    public ResponseEntity<Void> OptionCategoryRemove(Integer optionCategoryId) {
@sunlake123 수정해서 푸시했습니다!

2023-09-11 11:23 UTC, merged