Feat: 상품수량변경, 장바구니조회, 상품삭제 기능 추가
YesunPark/cafe-bom pull request #66
Opened 2023-09-10 11:26 UTC by thsu1084

### ☀️ 변경사항

**🌱 AS-IS**
상품 수량 변경, 장바구니 조회 , 상품 삭제 기능 필요

**🌷 TO-BE**
상품 수량 변경, 장바구니 조회, 상품 삭제 기능 구현

### 🗣️ Comment

### ⚡️ 테스트
 
- [x] 테스트 코드
- [x] 전체 테스트 성공
- [x] API 테스트

2023-09-10 12:31 UTC, YesunPark commented
영선님 지금 conflict들을 보니 최신 메인이랑 병합이 안되어있는 것 같은데
먼저 최신 메인이랑 병합부터 해주실 수 있을까요?
그래야 리뷰를 하는게 의미가 있을 것 같습니다!
병합하고 태그해서 알려주세요!

2023-09-10 12:40 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
> +        return ResponseEntity.ok(cartService.findType(token, cartAddForm, type));
controller를 따로안만들고 서비스로직으로하신이유가 있을까요.,...?!
잘 몰라서 물어봅니다!

2023-09-10 19:28 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
> +        return ResponseEntity.ok(cartService.findType(token, cartAddForm, type));
저희 사용자 기능이면 /auth가 붙어야 하지 않을까요?

2023-09-10 19:31 UTC, sunlake123 commented on src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
> +    public void successRemoveCartMemberNotExists() {
카트 삭제 실패 - 멤버가 존재하지 않음 이런 식이 되어야 하지 않을까요?
메서드명도 failRemobeCartMemberNotExists가 되어야 할 것 같습니다. 아래 나머지 테스트들도 수정이 필요해보여요!

2023-09-10 19:31 UTC, sunlake123 commented on src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
> +            .hasMessage(ErrorCode.MEMBER_NOT_EXISTS.getMessage());
static import 부탁드려여

2023-09-10 19:32 UTC, sunlake123 commented on src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
> +    public void successRemoveCartProductNotExists() {
여기도 설명과 메서드명 수정이 필요해보여요.

2023-09-10 19:32 UTC, sunlake123 commented on src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
> +    public void successFindCartEmptyCart() {
여기도 수정이 필요할 것 같습니다.

2023-09-10 19:32 UTC, sunlake123 commented on src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
> +            .hasMessage(ErrorCode.PRODUCT_NOT_EXISTS.getMessage());
요기도 static import!

2023-09-10 19:34 UTC, sunlake123 commented on src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
> +    public void successModifyCartProductNotExists() {
여기도 수정이 필요해 보입니다.

2023-09-10 19:34 UTC, sunlake123 commented on src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
> +            .hasMessage(ErrorCode.MEMBER_NOT_EXISTS.getMessage());
static import 부탁드려여

2023-09-10 19:34 UTC, sunlake123 commented on src/test/java/com/zerobase/cafebom/cart/service/CartServiceTest.java
> +            .hasMessage(ErrorCode.PRODUCT_NOT_EXISTS.getMessage());
요기도 static import

2023-09-10 19:36 UTC, sunlake123 commented on src/test/java/com/zerobase/cafebom/cart/controller/CartControllerTest.java
> +        // when
저희 // when이랑 // then 이전에 한 줄씩 띄우기로 했던 것 같아요!

2023-09-10 19:36 UTC, sunlake123 commented on src/test/java/com/zerobase/cafebom/cart/controller/CartControllerTest.java
> +        // then
요기두용

2023-09-10 19:37 UTC, sunlake123 commented
잘 읽었습니다. 코멘트 몇 개 달았어요!

2023-09-11 00:39 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +            throw new CustomException(ErrorCode.PRODUCT_NOT_EXISTS);
상품이 존재하지 않는 경우보다는 장바구니가 존재하지 않는경우가 더 맞지않을까 싶어요..!
상품이 존재하지 않는 경우의 예외처리는 위에서했으니까..!

2023-09-11 00:39 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +                        count++;
수량변경하는 부분인데 이부분이 필요한건가요..?!

2023-09-11 00:55 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +                    result = compare(optionIdList, optionIdCopyList);
저는 compare가 반환값이 0,1,-1로 되는걸로아는데 result type이 boolean인데 상관없나요?! 
잘 몰라서 여쭤봅니다!

2023-09-11 01:16 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +            throw new CustomException(ErrorCode.PRODUCT_NOT_EXISTS);
맞아요 장바구니에 상품이 존재하지 않습니다 이런 예외처리가 필요해보이네요!

2023-09-11 03:17 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +                        count++;
장바구니에서 사용자가 입력한 상품Id와 옵션 Id 리스트가 같은  상품을 찾아서 count 값만 사용자가 변경하기 원했던 값으로 변경해주는 구조 입니다!

2023-09-11 06:31 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +            throw new CustomException(ErrorCode.PRODUCT_NOT_EXISTS);
아 이 부분은 장바구니를 사용자 와 상품으로 검색 했을 때 아무것도 나오지 않는 경우라서 상품이 없다고 예외 처리를 했습니다!

2023-09-11 06:45 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +                    result = compare(optionIdList, optionIdCopyList);
아 함수 이름을 두 개의 리스트를 비교하는 거니까 compare라고 했는데 사실 다른 이름을 생각하지 못했습니다ㅠㅠ compare 함수에서 리스트를 String 형태로 변환해 equals  함수를 통해서 비교하는 거라 boolean 으로 타입을 정했습니다!

2023-09-11 07:13 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +                    result = compare(optionIdList, optionIdCopyList);
@thsu1084 이거는 제가  boolean에 있는compare메서드를 쓰신건줄 알고 착각했어요! 새로 비교하는 메서드를 만드셨군요..!답변감사합니다!

2023-09-11 07:36 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
> +    public ResponseEntity<List<CartProductDto>> cartSave(
담당자 주석 추가부탁드립니다

2023-09-11 07:40 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
> +    @PostMapping("/cart")
api 엔드포인트가 /auth/cart/cart 되는게 이상한 것 같아요...! 여기 `@PostMapping` 으로 수정해주셔야 할 것 같습니다

2023-09-11 07:47 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/controller/form/CartAddForm.java
> +}
Validation 추가해주세요...!

2023-09-11 07:47 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/domain/Cart.java
> +    public void setQuantity(Integer count){this.productCount = count; }
productCount를 수정하는 메서드니까 setProductCount라고 하는게 낫지 않을까요?

2023-09-11 07:47 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/domain/CartRepository.java
> +
두 줄 띄우신 거 한줄만 띄우도록 수정 부탁드립니다

2023-09-11 07:49 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +    }
이 부분은 없어져야 하는 코드입니다..
컨트롤러가 하나로 합쳐져버려서 짜신 것 같은데
이렇게 하지말고 컨트롤러를 나눠주셔야해요!

2023-09-11 07:49 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +    // 장바구니에 저장된 상품 삭제-youngseon-2023-09-10
장바구니 상품 삭제라고만 해주시면 됩니다
// 장바구니 상품 삭제-youngseon-23.09.10

주석 날짜 형식도 계속 안맞아서 확인 부탁드려요ㅠㅠ

2023-09-11 07:50 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +            .orElseThrow(() -> new CustomException(ErrorCode.MEMBER_NOT_EXISTS));
에러코드 전부다 static Import로 수정부탁드립니다!

2023-09-11 07:54 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +    public List<Integer> from(Cart cart) {
컨트롤러에서 사용되는 메서드가 아니라 CartService 내에서만 사용되는 메서드들은 public 이 아니라 private으로 선언 부탁드립니다

2023-09-11 07:55 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +    // 리스트가 동일한지 비교-youngseon-2023-09-10
무슨 리스트가 동일한지 비교하는건지 주석을 달아주시면 좋을 것 같습니다.
그리고 동일하게 private으로 선언부탁드려요

2023-09-11 10:44 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +            throw new CustomException(ErrorCode.PRODUCT_NOT_EXISTS);
제가 생각한 건 사용자가 삭제 하고자 하는  상품이 없는 경우를 생각해서 저렇게 했습니다!

2023-09-11 12:23 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
> +    @GetMapping("{cartId}")
"/{cartId}"가 아니여도 데이터가 들어가지나요...?

2023-09-11 12:24 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
> +    @GetMapping("{cartId}")
Postman으로 했을 때 잘 돌아가서 발견을 못했네요! 수정하겠습니다!

2023-09-11 12:40 UTC, thsu1084 commented on src/test/java/com/zerobase/cafebom/cart/controller/CartControllerTest.java
> +//public class CartControllerTest {
@YesunPark 수정 했습니다!

2023-09-11 19:35 UTC, sunlake123 commented on src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
> +        return ResponseEntity.ok(cartService.findCart(token,cartId));
이 파일 요기 코드 정렬 한 번만 부탁드립니다! 콤마 뒤에 띄어쓰기가 없네욤

2023-09-11 20:12 UTC, sunlake123 requested changes
영선님 혹시 지금 고치시고 계실지 모르겠지만 코멘트 남깁니다!

우선 장바구니 "목록 조회"는 제가 이미 만들었습니다.

저희 ERD상 장바구니 하나란

a라는 사람이 b라는 상품을 c, d, e의 옵션을 추가해 넣어놨다! 라는 것이고
저는 a라는 사람이 넣어놓은 품목들 (얼음 많이 커피, 저지방 우유 카페라떼, 아샷추 등)
전체를 조회하는 기능이구요. (`cartRepository.findAllByMember(Long memberId);`)

아마 단건 조회 기능을 만들려고 하셨던 것 같습니다.

코드로 들어가 controller를 보시면 "장바구니 조회"라는 기능이 있고 cartId를 `@PathVariable`로 받고 있네요. 이게 아마 제가 만든 장바구니 목록 조회 기능을 통해 출력된 a라는 사람의 장바구니 목록에서 "하나의 상품"을 클릭해 cartId로 단건 조회를 하는 기능이겠죠?

그런데 응답 형식이 List<CartProductDto>로 되어 있어요. 그래서 CartProductDto를 보니 안에 productId가 있습니다. Dto 하나에 상품Id가 있다는 건 List<Dto>는 상품 여러 종류가 들어있다는 건데, 여기서 단건 조회가 아니게 돼버린 것 같습니다.

다음으로 service에 있는 
```
// 장바구니에 저장된 상품 목록 조회-youngseon-23.09.10
public List<CartProductDto> findCart(String token, Long cartId)
```
를 보면 주석이 저장된 상품 목록 조회로 되어 있어요. 위에서 언급했듯 저희의 장바구니 하나는 하나의 상품을 어떤 옵션을 추가해서 몇 개를 샀느냐이기 때문에 cartId 하나로 상품 목록을 뽑아오는 건 어려움이 있어 보여요.

---
장바구니 단건 조회를 하려면

우선 memberId로 검색해 없는 유저 -> MEMBER_NOT_EXISTS로,
cartId가 없다면 -> CART_IS_EMPTY가 아닌 CART_NOT_EXISTS로,
있다면 cartOption에서 cartId로 검색해 이 장바구니(상품)에 어떤 옵션이 추가됐는지를
끌어와서 Dto를 만들어야 할 것 같습니다.

2023-09-12 03:23 UTC, rkoji commented on build.gradle
> +	implementation 'org.jetbrains:annotations:24.0.0'
이거는 삭제하시는거죠?!

2023-09-12 03:24 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
@YesunPark 
`Cart otherCart = cartRepository.findById(cartId)
            .orElseThrow(() -> new CustomException(CART_IS_EMPTY));

        List<CartProductDto> cartProductDtoList = new ArrayList<>();

        CartProductDto cartProductDto = CartProductDto.from(otherCart);

        List<CartOption> cartOptionList = cartOptionRepository.findByCart(otherCart);

        List<Integer> cartOptionIds = new ArrayList<>();

        for (CartOption cartOption : cartOptionList) {
            cartOptionIds.add(cartOption.getOption().getId());
        }

        for (Integer optionId : cartOptionIds) {
            cartProductDto.addOptionId(optionId);
        }

            cartProductDtoList.add(cartProductDto);
`
이 부분이 cartId로 cart 객체를 찾고 찾은 cart 객체에서 필요한 정보만 dto에 저장하고  이 객체를 가지고 cartOptionRepository에서 cart 객체가 가지는 option객체들을 찾아 리스트에 저장하고 저장된 리스트에서 option id 만 dto에 있는 리스트에 저장하는 구조로 했습니다!

2023-09-12 03:27 UTC, thsu1084 commented on build.gradle
> +	implementation 'org.jetbrains:annotations:24.0.0'
넵!

2023-09-12 05:08 UTC, rkoji commented on src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
> +        @RequestBody @Valid CartAddForm cartAddForm,
조회하는데 서비스로직 보니까 CartAddForm은 안쓰시는거같아요..!! catId로 조회하시는거 같아보여서 폼은 안받와도되지않을까요..?!

2023-09-12 05:11 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
> +        @RequestBody @Valid CartAddForm cartAddForm,
수정하겠습니다!

2023-09-12 05:48 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/controller/CartController.java
> +        @RequestBody @Valid CartAddForm cartAddForm,
@rkoji 수정했습니다!

2023-09-12 06:23 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
@thsu1084 엇 제가 이 부분 여쭤본 적이 있었나요..? ㅎㅎ 😂

2023-09-12 06:26 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
@YesunPark 진짜 너무 죄송해요ㅠㅠ 댓글이 너무 많아서 착각했습니다!

2023-09-12 06:27 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
@sunlake123 우영님 확인 부탁드립니다!

2023-09-12 09:00 UTC, YesunPark requested changes
컨트롤러들에 notes가 없어서 request changes 달았습니다! 
추가되면 다시 태그 부탁드리겠습니다
나머지는 확인됐습니다 ㅎㅎ
고생하셨어요!! ㅠㅠ

2023-09-13 04:23 UTC, YesunPark approved these changes
추가 커밋으로 notes 해주신 것 확인했습니다!
고생하셨습니다 😂👍

2023-09-13 07:26 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
@sunlake123 우영님 최종 커밋 확인 해주세요! saveCart를 통해 상품 자체가 장바구니에 없는 경우 상품 객체를 생성해  디비에 넣어주고 상품과 옵션이 모두 같은 데이터가 있는 경우 사용자가 입력한  수량을 더해주고 같은 상품은 있지만 옵션까지 같은 상품이 없는 경우 상품 객체를 생성해 디비에 넣어주는 로직으로 만들었습니다! 그리고 요청하신 카트 아이디로 데이터를 조회 할 때 카트 아이디가 디비에 존재하지 않는 경우 카트가 존재하지 않는다는 에러코드 추가했습니다! 그리고 반환 값 list 에서 dto로 변경했습니다!

2023-09-13 08:04 UTC, YesunPark requested changes
확인했습니다! Cart 엔티티에 상품 수량업데이트하는 로직이 두개인 거랑 
에러코드 통일되지 않은 것 때문에 request changes 걸었습니다ㅠㅠ
확인 후 태그 부탁드려요!

2023-09-13 08:04 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/cart/service/CartService.java
> +    public List<CartProductDto> saveCart(String token, CartAddForm cartAddForm) {
장바구니에 상품 등록만 하는 메서드니까 addCart가 더 맞는 것 같습니다~!

2023-09-13 08:04 UTC, YesunPark commented on src/main/java/com/zerobase/cafebom/exception/ErrorCode.java
> +    CART_DOES_NOT_EXIST("장바구니가 존재하지 않습니다.",BAD_REQUEST),
다른 메세지랑 통일되게 존재하지 않는 장바구니입니다. 라고 부탁드리겠습니다!

2023-09-13 08:04 UTC, YesunPark commented on src/test/java/com/zerobase/cafebom/cart/controller/CartControllerTest.java
> +    @DisplayName("상품 넣기 성공")
장바구니 상품 추가 성공으로 하시면 더 이해하기 쉬울 것 같습니다 :)

2023-09-13 08:08 UTC, thsu1084 commented on src/main/java/com/zerobase/cafebom/cart/domain/Cart.java
> +    }
setProductCount는 상품 수량을 변경할 때 사용하는 메소드이고 addCount는 기존 값에서 사용자가 원하는 수량만큼을 더 할때 사용하는 함수 입니다! 그래서 setProductCount는 modifyCart 용이고 addCount는 saveCart 용입니다!

2023-09-13 10:19 UTC, YesunPark approved these changes
고생하셨습니다~!

2023-09-13 10:47 UTC, sunlake123 approved these changes

2023-09-13 11:19 UTC, bingsoo95 approved these changes
확인했습니다 고생하셨습니다!

2023-09-13 12:43 UTC, merged