Feat: Order Entity/Repository/RepositoryTest 완성
YesunPark/cafe-bom pull request #7
Opened 2023-08-15 16:22 UTC by bingsoo95

### ☀️ 변경사항

**🌱 AS-IS**
- Order 관련 Entity/Repository/RepositoryTest 부재

**🌷 TO-BE**
- Order 관련 Entity/Repository/RepositoryTest 생성
- `gitkeep` 파일 삭제

### 🗣️ Comment

- menus 엔티티를 HashMap 형태로 저장하는 부분에 대해 추가적으로 공부하고 수정하려고 합니다.
- DB 상에서 order가 예약어로 지정되어 있어 order를 테이블명으로 그대로 사용할 시 에러가 발생하는 문제점을 발견, 이 문제를 해결하기 위해 @Table어노테이션을 붙인 후 테이블명 사이에 백틱을 넣어 해결해보았습니다.
### ⚡️ 테스트
 
- [x] 테스트 코드
- [x] 전체 테스트 성공
- [ ] API 테스트

2023-08-15 17:17 UTC, YesunPark requested changes
몇가지 질문사항 남겼습니다 :)
Orderstatus 분류나 type 폴더 위치 같은 경우는
꼭 수정이 되고 머지되어야 할 것 같아서 request changes로 리뷰 달겠습니다!

2023-08-15 17:17 UTC, YesunPark commented on src/main/java/com/zerobase/CafeBom/order/domain/entity/Order.java
> +@Table(name = "`order`")
이 부분 좀 더 알아보고 머지한다고 하신 것 같은데 이렇게 하기로 확정되신 걸까요?

2023-08-15 17:17 UTC, YesunPark commented on src/main/java/com/zerobase/CafeBom/order/domain/entity/Order.java
> +import com.zerobase.CafeBom.order.domain.type.OrderStatus;
저희 type 폴더는 도메인별로 하나씩 갖고 있는게 아니라 가장 상위폴더에 type폴더 만들고 하나 넣어두고 enum들은 다 거기서 관리하기로 한 것 아니었나요?!

2023-08-15 17:17 UTC, YesunPark commented on src/main/java/com/zerobase/CafeBom/order/domain/type/OrderStatus.java
> +  COMPLETED,
보니까 주문취소, 주문 수락 전, 수령완료(?)
만 있는 것 같은데
준비 중, 준비완료 는 어떻게 구분하나요?

2023-08-15 17:43 UTC, bingsoo95 commented on src/main/java/com/zerobase/CafeBom/order/domain/entity/Order.java
> +import com.zerobase.CafeBom.order.domain.type.OrderStatus;
어제 만들어 놓았던거라 위치 수정을 못했네요 수정해 놓겠습니다.

2023-08-15 17:44 UTC, bingsoo95 commented on src/main/java/com/zerobase/CafeBom/order/domain/type/OrderStatus.java
> +  COMPLETED,
추가해서 커밋하겠습니다!

2023-08-15 17:47 UTC, bingsoo95 commented on src/main/java/com/zerobase/CafeBom/order/domain/entity/Order.java
> +@Table(name = "`order`")
그 전에 피드백 받았던 `@Entity(name="ORDER)` 이 어노테이션을 사용해도 에러가 나서 일단 구글링해봤던 위에 있는 방법으로 커밋해놓았습니다. 한번 더 좋은 방법이 있는지 찾아보고 반영해서 pr 내용에 작성해놓을게요~

2023-08-16 10:55 UTC, YesunPark commented on src/main/java/com/zerobase/CafeBom/type/OrderStatus.java
> +  RECEIVED
혹시 start 상태는 뭔가요!?!?
제 생각엔 관리자가 수락(조리 시작)을 누르면 waiting에서 바로 Cooking으로 가야하지 않을까 싶은데 start 상태는 어떤 상태인지 궁금합니당

2023-08-16 10:55 UTC, YesunPark commented on src/main/java/com/zerobase/CafeBom/type/OrderStatus.java
> +  RECEIVED
@bingsoo95

2023-08-16 11:11 UTC, bingsoo95 commented on src/main/java/com/zerobase/CafeBom/type/OrderStatus.java
> +  RECEIVED
네, 말씀해주신대로 start 상태는 필요없어 보이네요. 수정하겠습니다!

2023-08-16 14:42 UTC, YesunPark commented on src/main/java/com/zerobase/CafeBom/type/OrderStatus.java
> +  RECEIVED
CANCELED
WAITING
COOKING
PREPARED
FINISHED

2023-08-17 11:00 UTC, YesunPark approved these changes

2023-08-17 11:02 UTC, YesunPark commented
민수님 이 브랜치에 커밋이 되게 많은데, 메인에 머지하실 때는 꼭 squash merge 옵션으로 해주시고 필요없는 (자잘한) 커밋 제목들은 삭제하고 핵심만 남겨서 커밋부탁드릴게요! 수고하셨습니다
주문 엔티티는 이걸로...되겠죠..? 😭

2023-08-18 12:48 UTC, rkoji commented on src/main/java/com/zerobase/CafeBom/type/OrderCookingTime.java
> +  _20_TO_25_MINUTES("10분 ~ 15분"),
여기부분 15~20이랑 20~25가 수정이 안된거같아요!

2023-08-18 12:49 UTC, bingsoo95 commented on src/main/java/com/zerobase/CafeBom/type/OrderCookingTime.java
> +  _20_TO_25_MINUTES("10분 ~ 15분"),
아 제가 수정을 빼먹었네요 수정해놓겠습니다!

2023-08-18 12:51 UTC, rkoji approved these changes

2023-08-18 13:15 UTC, thsu1084 approved these changes

2023-08-18 13:19 UTC, merged